# Generated by Django 5.2.8 on 2025-11-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='response_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
